#!/bin/bash
# WSL2 代理配置脚本
# 用于自动化配置 WSL2 代理环境（NAT 模式）
# 使用方法：bash setup-wsl2-proxy.sh

set -e

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 打印带颜色的消息
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 获取 WSL2 默认网关（宿主机 IP）
get_host_ip() {
    ip route show | grep default | awk '{print $3}'
}

# 交互式确认
confirm() {
    local message="$1"
    local default="${2:-y}"
    
    while true; do
        if [ "$default" = "y" ]; then
            read -p "$message [Y/n]: " choice
        else
            read -p "$message [y/N]: " choice
        fi
        
        case "${choice:-$default}" in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "请输入 Y 或 N";;
        esac
    done
}

# 主函数
main() {
    echo -e "${GREEN}"
    echo "=========================================="
    echo "   WSL2 代理配置脚本 (NAT 模式)"
    echo "=========================================="
    echo -e "${NC}"
    
    # 步骤 1: 检测宿主机 IP
    print_info "步骤 1: 检测宿主机 IP 地址..."
    AUTO_HOST_IP=$(get_host_ip)
    
    if [ -z "$AUTO_HOST_IP" ]; then
        print_error "无法获取宿主机 IP，请检查网络连接"
        exit 1
    fi
    
    print_success "自动检测到宿主机网关 IP: ${AUTO_HOST_IP}"
    
    # 交互式确认 IP
    echo ""
    print_info "如果自动检测的 IP 无法使用，可以手动指定宿主机 IP"
    echo "（通常使用自动检测的 IP 即可，如果代理软件绑定在物理网卡上，则需要手动指定物理 IP）"
    echo ""
    
    if confirm "是否使用自动检测的 IP (${AUTO_HOST_IP})？"; then
        HOST_IP="${AUTO_HOST_IP}"
    else
        echo ""
        print_info "请输入宿主机 IP 地址（例如：192.168.0.56）"
        read -p "宿主机 IP: " HOST_IP
        
        if [ -z "$HOST_IP" ]; then
            print_error "IP 地址不能为空"
            exit 1
        fi
    fi
    
    print_success "将使用宿主机 IP: ${HOST_IP}"
    
    # 步骤 2: 获取代理端口
    echo ""
    print_info "步骤 2: 配置代理端口"
    echo "请输入你的代理软件端口号（Clash Verge 默认：7897, 7890, 7898）"
    
    while true; do
        read -p "代理端口 [7897]: " PROXY_PORT
        PROXY_PORT=${PROXY_PORT:-7897}
        
        # 验证端口号
        if [[ "$PROXY_PORT" =~ ^[0-9]+$ ]] && [ "$PROXY_PORT" -ge 1 ] && [ "$PROXY_PORT" -le 65535 ]; then
            print_success "代理端口：${PROXY_PORT}"
            break
        else
            print_error "请输入有效的端口号 (1-65535)"
        fi
    done
    
    # 步骤 3: 备份现有配置
    echo ""
    print_info "步骤 3: 备份现有配置..."
    
    BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
    
    if [ -f ~/.bashrc ]; then
        cp ~/.bashrc ~/.bashrc.backup.${BACKUP_DATE}
        print_success "已备份 ~/.bashrc -> ~/.bashrc.backup.${BACKUP_DATE}"
    fi
    
    if [ -f ~/.ssh/config ]; then
        cp ~/.ssh/config ~/.ssh/config.backup.${BACKUP_DATE}
        print_success "已备份 ~/.ssh/config -> ~/.ssh/config.backup.${BACKUP_DATE}"
    fi
    
    # 步骤 4: 配置 Shell 代理脚本
    echo ""
    print_info "步骤 4: 配置 Shell 代理脚本..."
    
    # 检查是否已存在代理配置
    if grep -q "WSL2_HOSTIP" ~/.bashrc 2>/dev/null; then
        print_warning "检测到 ~/.bashrc 中已存在代理配置"
        if confirm "是否覆盖现有配置？"; then
            # 删除旧的代理配置
            sed -i '/^# WSL2 Proxy Configuration/,/^# End WSL2 Proxy Configuration/d' ~/.bashrc
            print_info "已删除旧的代理配置"
        else
            print_info "保留现有配置，跳过此步骤"
        fi
    fi
    
    # 添加新的代理配置
    cat >> ~/.bashrc << EOF

# WSL2 Proxy Configuration
# Generated by setup-wsl2-proxy.sh on $(date)
# ==========================

# 宿主机 IP 地址（固定值，避免动态获取失败）
export WSL2_HOSTIP=${HOST_IP}

# 代理端口配置（根据实际代理软件修改）
export WSL2_PROXY_PORT=${PROXY_PORT}

# 一键开启代理
proxy_on() {
    local hostip="\${WSL2_HOSTIP}"
    local port="\${WSL2_PROXY_PORT}"
    
    # 设置环境变量
    export http_proxy="http://\${hostip}:\${port}"
    export https_proxy="http://\${hostip}:\${port}"
    export ALL_PROXY="socks5://\${hostip}:\${port}"
    export HTTP_PROXY="http://\${hostip}:\${port}"
    export HTTPS_PROXY="http://\${hostip}:\${port}"
    
    # 配置 Git 代理
    git config --global http.proxy "http://\${hostip}:\${port}"
    git config --global https.proxy "http://\${hostip}:\${port}"
    
    # 配置 pip 代理（可选）
    mkdir -p ~/.pip
    cat > ~/.pip/pip.conf <<PIPCONF
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
[install]
proxy = http://\${hostip}:\${port}
PIPCONF
    
    # 配置 npm 代理（可选）
    npm config set proxy "http://\${hostip}:\${port}" 2>/dev/null || true
    npm config set https-proxy "http://\${hostip}:\${port}" 2>/dev/null || true
    
    echo -e "\033[32m✓ WSL2 代理已开启\033[0m"
    echo -e "  宿主机 IP: \033[36m\${hostip}\033[0m"
    echo -e "  代理端口：\033[36m\${port}\033[0m"
    echo -e "  代理类型：\033[36mHTTP/Socks5\033[0m"
}

# 一键关闭代理
proxy_off() {
    # 清除环境变量
    unset http_proxy https_proxy ALL_PROXY HTTP_PROXY HTTPS_PROXY
    
    # 清除 Git 代理
    git config --global --unset http.proxy 2>/dev/null
    git config --global --unset https.proxy 2>/dev/null
    
    # 清除 pip 代理
    rm -f ~/.pip/pip.conf
    
    # 清除 npm 代理
    npm config delete proxy 2>/dev/null || true
    npm config delete https-proxy 2>/dev/null || true
    
    echo -e "\033[31m✗ WSL2 代理已关闭\033[0m"
}

# 查看当前代理状态
proxy_status() {
    if [ -n "\$http_proxy" ]; then
        echo -e "\033[32m✓ 代理已开启\033[0m"
        echo -e "  HTTP 代理：\033[36m\${http_proxy}\033[0m"
        echo -e "  HTTPS 代理：\033[36m\${https_proxy}\033[0m"
        
        # 测试连通性
        echo -e "\n\033[33m测试连接...\033[0m"
        if curl -s --connect-timeout 3 -I https://www.google.com >/dev/null 2>&1; then
            echo -e "  Google: \033[32m✓ 可达\033[0m"
        else
            echo -e "  Google: \033[31m✗ 不可达\033[0m"
        fi
        
        # GitHub SSH 测试：只检查网络是否畅通，不关心认证结果
        # 只要能收到 GitHub 的响应（包括 Permission denied）就认为代理正常
        local ssh_output
        ssh_output=$(ssh -o ConnectTimeout=5 -T git@github.com 2>&1)
        if echo "$ssh_output" | grep -qE "Permission denied|successfully authenticated|Hi .*!"; then
            echo -e "  GitHub SSH: \033[32m✓ 可达\033[0m (网络畅通)"
        else
            echo -e "  GitHub SSH: \033[31m✗ 不可达\033[0m"
            echo -e "    错误：\033[33m$ssh_output\033[0m"
        fi
    else
        echo -e "\033[31m✗ 代理未开启\033[0m"
        echo "  使用 'proxy_on' 命令开启代理"
    fi
}

# End WSL2 Proxy Configuration
# ==========================

EOF
    
    print_success "Shell 代理脚本配置完成"
    
    # 步骤 5: 安装 netcat
    echo ""
    print_info "步骤 5: 检查并安装 netcat 工具..."
    
    if ! command -v nc &> /dev/null; then
        print_warning "未检测到 netcat，正在安装..."
        sudo apt update && sudo apt install netcat-openbsd -y
        print_success "netcat-openbsd 安装完成"
    else
        # 检查版本
        if nc -h 2>&1 | grep -q "OpenBSD"; then
            print_success "netcat-openbsd 已安装"
        else
            print_warning "检测到非 OpenBSD 版本的 netcat，可能需要重新安装"
            if confirm "是否安装 netcat-openbsd？"; then
                sudo apt update && sudo apt install netcat-openbsd -y
                print_success "netcat-openbsd 安装完成"
            fi
        fi
    fi
    
    # 步骤 6: 配置 SSH 代理转发
    echo ""
    print_info "步骤 6: 配置 SSH 代理转发..."
    
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    
    # 检查是否已存在 GitHub 配置
    if grep -q "Host github.com" ~/.ssh/config 2>/dev/null; then
        print_warning "检测到 ~/.ssh/config 中已存在 GitHub 配置"
        if confirm "是否覆盖现有配置？"; then
            # 删除旧的 GitHub 代理配置
            sed -i '/^# GitHub SSH Proxy Configuration/,/^# End GitHub SSH Proxy Configuration/d' ~/.ssh/config
            print_info "已删除旧的 GitHub 配置"
        else
            print_info "保留现有配置，跳过此步骤"
        fi
    fi
    
    # 添加 SSH 配置
    cat >> ~/.ssh/config << EOF

# GitHub SSH Proxy Configuration
# Generated by setup-wsl2-proxy.sh on $(date)
# ==========================

Host github.com
    User git
    Hostname github.com
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes
    # 使用 Socks5 代理，使用配置的宿主机 IP
    ProxyCommand nc -X 5 -x ${HOST_IP}:${PROXY_PORT} %h %p

# GitLab SSH Proxy Configuration (可选)
Host gitlab.com
    User git
    Hostname gitlab.com
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes
    ProxyCommand nc -X 5 -x ${HOST_IP}:${PROXY_PORT} %h %p

# Gitee SSH Proxy Configuration (可选，如不需要可删除)
Host gitee.com
    User git
    Hostname gitee.com
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes
    ProxyCommand nc -X 5 -x ${HOST_IP}:${PROXY_PORT} %h %p

# 其他所有主机直连（不使用代理）
Host *
    ProxyCommand none

# End GitHub SSH Proxy Configuration
# ==========================

EOF
    
    chmod 600 ~/.ssh/config
    print_success "SSH 代理转发配置完成"
    
    # 步骤 7: 使配置生效
    echo ""
    print_info "步骤 7: 使配置生效..."
    echo ""
    print_warning "重要提示："
    echo "  脚本中的 source 命令无法影响当前 shell 会话"
    echo "  请在脚本执行完毕后，手动执行以下命令之一："
    echo ""
    echo "    source ~/.bashrc    # 或者重新打开终端窗口"
    echo ""
    
    # 完成
    echo ""
    echo -e "${GREEN}"
    echo "=========================================="
    echo "   配置完成！"
    echo "=========================================="
    echo -e "${NC}"
    echo ""
    print_info "常用命令："
    echo "  proxy_on       - 开启代理"
    echo "  proxy_off      - 关闭代理"
    echo "  proxy_status   - 查看代理状态"
    echo ""
    print_info "测试连接："
    echo "  ssh -T git@github.com"
    echo "  curl -I https://www.google.com"
    echo ""
    print_warning "注意事项："
    echo "  1. 确保宿主机的代理软件已开启 'Allow LAN'"
    echo "  2. 如果连接失败，请检查 Windows 防火墙设置"
    echo "  3. 新打开的终端窗口会自动加载代理配置"
    echo ""
}

# 执行主函数
main
